services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      target: ssr-release
    restart: always
    env_file: '.env'
    environment:
      PHP_OPCACHE_ENABLE: '1'
      SSL_MODE: 'mixed'
    volumes:
      - 'storage-public:/var/www/html/storage/app/public/'
      - 'storage-sessions:/var/www/html/storage/framework/sessions'
      - 'storage-logs:/var/www/html/storage/logs'
    labels:
      # Adjust "laravel-primevue" service name as needed
      - 'traefik.enable=true'
      - 'traefik.http.routers.laravel-primevue.rule=Host(`${APP_DOMAIN}`)'
      - 'traefik.http.routers.laravel-primevue.entrypoints=websecure'
      - 'traefik.http.routers.laravel-primevue.tls=true'
      - 'traefik.http.routers.laravel-primevue.tls.certresolver=letsencrypt'
      - 'traefik.http.services.laravel-primevue.loadbalancer.server.port=8080' # exposed http port from serversideup image
      # Health check
      - 'traefik.http.services.laravel-primevue.loadbalancer.healthcheck.path=/healthcheck'
      - 'traefik.http.services.laravel-primevue.loadbalancer.healthcheck.interval=30s'
      - 'traefik.http.services.laravel-primevue.loadbalancer.healthcheck.timeout=5s'
      - 'traefik.http.services.laravel-primevue.loadbalancer.healthcheck.scheme=http'
    networks:
      - proxy
    depends_on:
      - pgsql

  pgsql:
    image: postgres:17
    restart: always
    ports:
      - '${DB_FORWARD_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - proxy
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}']
      retries: 3
      timeout: 5s

volumes:
  postgres-data:
  storage-public:
  storage-sessions:
  storage-logs:

networks:
  proxy:
    name: traefik_network
    external: true